title: "エンジニアのためのデザイン入門"
summary: |-
  ・まずはセンスで作ってみる
  ・ゲシュタルト心理学
  ・階層化
  　・情報の優先度
  　・意識誘導（意図的に情報伝達を操作する）
  　・隣接
  　・対比
  　　・明暗対比
  　　・補色対比（明暗対比より弱い）
  　・濃い色は手前にあるように見える
  ・印象操作
  　・色
  　・フォント
  　・丸っこさ
topics: []
published: false
price: 0
toc_depth: 2
chapters: []
allow_override: true